// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Propagator.Infrastucture.DataContext;

#nullable disable

namespace Propagator.Infrastucture.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20250121071952_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Propagator.Infrastucture.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Salary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 1000
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 2000
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 3000
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 4000
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 5000
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 6000
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 7000
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 8000
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 9000
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 10000
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 11000
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 12000
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 13000
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 14000
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 15000
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 16000
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 17000
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 18000
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 19000
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "John",
                            LastName = "Doe",
                            Salary = 20000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
